server/serwer/serwer/Models/ImagesViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace serwer.Models
{
    public class UploadFileViewModel
    {
        //public SelectList algorithms { get; set; }
        public Dictionary<String, String> algorithms { get; set; }
        public string selectedAlgorithm { get; set; }
    }

    public class ImagesDownloadDetails
    {
        public List<string> items { get; set; }
        public string originalImageExtension { get; set; }
        public string processedImageExtension { get; set; }
        public string removeImageName { get; set; }
        public string processedImageDataInJSON { get; set; }
    }
}

server/serwer/serwer/Controllers/ImagesController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.IO;
using serwer.Models;
using serwer.Config;
using System.Collections.Generic;
using System.Threading;
using serwer.Helpers;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using System.Drawing;

namespace serwer.Controllers
{
    [Authorize]
    public class ImagesController : Controller
    {
        // This action represents a view for image uploading
        [HttpGet]
        public ActionResult UploadFile()
        {
            UploadFileViewModel uploadFileViewModel = new UploadFileViewModel(); // ViewModel for passing a list of available matlab algorithms on the server to the client

            //string[] files = Directory.GetFiles(Server.MapPath(ServerConfigurator.matlabScriptsPath)); // Read all matlab algorithms available on server
            string[] files = Directory.GetFiles(ServerConfigurator.matlabScripts); // Read all matlab algorithms available on server

            //List<SelectListItem> list = new List<SelectListItem>(); // create list of algorithms later passed to the view
            //list.Add(new SelectListItem { Selected = true, Text = "Wybierz algorytm", Value = "-1" }); // default (first) value "Wybierz algorytm"

            //foreach (var file in files) // add all algorithm to the list
            //{
            //    string fileName = Path.GetFileNameWithoutExtension(file);
            //    list.Add(new SelectListItem { Selected = false, Text = fileName, Value = fileName });
            //}

            //uploadFileViewModel.algorithms = new SelectList(list); // save list to the viewmodel "SelectList" object

            Dictionary<string, string> list = new Dictionary<string, string>(); // create list of algorithms later passed to the view
            //list.Add(new SelectListItem { Selected = true, Text = "Wybierz algorytm", Value = "-1" }); // default (first) value "Wybierz algorytm"

            foreach (var file in files) // add all algorithm to the list
            {
                string fileName = Path.GetFileNameWithoutExtension(file);
                list.Add(fileName, fileName);
            }

            uploadFileViewModel.algorithms = list; // save list to the viewmodel "SelectList" object

            return View(uploadFileViewModel);
        }

        // This action handles a HTTP POST request with image uploaded
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadFile(HttpPostedFileBase file, UploadFileViewModel model)
        {
            try
            {
                // Check if file (image) is: not null, not empty and has an extension (lower case) which is supported by server (checked by regex)
                if(Core.checkIfReceivedFileHasValidExtension(file))
                {
                    Image.FromStream(file.InputStream); // Try to create Image - if "file" is not valid - then Image creation fails and exception will be thrown

                    string user = User.Identity.Name; // fetches the user login, which is currently logged in. It is used to decide into which directory the image should be saved
                                       
                    if (!Core.checkIfMatlabScriptExistsOnServer(ServerConfigurator.matlabScripts, model.selectedAlgorithm)) // Check if given algorithm exists on the server
                    {
                        ViewBag.Message = "Błąd - nie ma takiego algorytmu na serwerze";
                        return View("imagesView", this.getImages());
                    }

                    Core.startProcessingImage(file, user, model.selectedAlgorithm); // starts exact image processing. To start image processing we need image 
                                                                                    // to be processed (file), which user requested processing (user) and which algorithm 
                                                                                    // to use for processing (model.selectedAlgorithm)
                    ViewBag.Message = "Pomyślnie przesłano obraz na serwer";
                    return RedirectToAction("imagesView");
                }
                else
                {
                    // Invalid image received from client
                    return RedirectToAction("UploadFile");
                }                
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error during sending image to server";
                return RedirectToAction("UploadFile");
            }
        }

        [HttpGet]
        public ActionResult ImagesView()
        {
            return View(this.getImages());
        }

        // Returns an image which is out of the server webroot
        [HttpGet]
        public FileResult DownloadImage(string ImageName)
        {
            try
            {
                return File(ServerConfigurator.usersStorage + User.Identity.Name + ServerConfigurator.directoryPathSeparator + ImageName, System.Net.Mime.MediaTypeNames.Application.Octet, ImageName);
            }
            catch (Exception)
            {
                return null;
            }
        }


        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /// </summary>
        /// <returns></returns>
        // In final version I have removed feature of removing images from server

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult RemoveImage(ImagesDownloadDetails imagesDownloadDetails)
        //{
        //    // Using regular expression check if correct filename was received from client for removing image
        //    string pattern = "(^" + ServerConfigurator.originalImageName + "\\." + ServerConfigurator.supportedImageExtensions + "$)|(^" + ServerConfigurator.processedImageName + "\\." + ServerConfigurator.supportedImageExtensions + "$)";

        //    if (!Regex.Match(imagesDownloadDetails.removeImageName, pattern).Success)
        //        return RedirectToAction("ImagesView");

        //    try
        //    {
        //        //System.IO.File.Delete(Server.MapPath(imagesDownloadDetails.removeImagePath));
        //        System.IO.File.Delete(ServerConfigurator.usersStorage + User.Identity.Name + ServerConfigurator.directoryPathSeparator + imagesDownloadDetails.removeImageName);
        //    }
        //    catch (ArgumentException) { }
        //    //catch (ArgumentNullException) { } // 
        //    catch (DirectoryNotFoundException) { }
        //    catch (IOException) { }
        //    catch (NotSupportedException) { }
        //    //catch (PathTooLongException) { } // already catched by IOException
        //    catch (UnauthorizedAccessException) { }
        //    catch (Exception) { }

        //    return RedirectToAction("ImagesView");
        //}
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        // Saves all images names in directory to viewmodel object to retrieve them during displaying images in the view named "ImagesView"
        // There SHOULD ALWAYS be only two images per user on the server, but this method supports more, than two
        private ImagesDownloadDetails getImages()
        {
            ImagesDownloadDetails imagesDownloadDetails = new ImagesDownloadDetails(); // New ViewModel object for passing a list of images to view to generate links
            imagesDownloadDetails.items = new List<string>();
            imagesDownloadDetails.processedImageDataInJSON = null; // initialize with null. Null is treated as not-to-display in the view (when null - then it won't be displayed in the view)

            //var dir = new DirectoryInfo(Server.MapPath(ServerConfigurator.imageStoragePath + User.Identity.Name + "/"));
            var dir = new DirectoryInfo(ServerConfigurator.usersStorage + User.Identity.Name + ServerConfigurator.directoryPathSeparator);
            FileInfo[] fileNames = null;
            try
            {
                fileNames = dir.GetFiles("*.*"); // list all files in personal directory 
            }catch(DirectoryNotFoundException) // when directory not exists
            {
                return imagesDownloadDetails;
            }            

            foreach (var file in fileNames)
            {
                imagesDownloadDetails.items.Add(file.Name); // saving names of images
                if (file.Name.StartsWith(ServerConfigurator.originalImageName))
                {
                    imagesDownloadDetails.originalImageExtension = file.Extension; // saving extension of original image. Extension is saved with dot at the beginning, i.e ".jpg"
                }
                if (file.Name.StartsWith(ServerConfigurator.processedImageName))
                {
                    imagesDownloadDetails.processedImageExtension = file.Extension; // saving extension of processed image. Extension is saved with dot at the beginning, i.e ".jpg"
                }

server/serwer/serwer/Views/Images/ImagesView.cshtml
@model serwer.Models.ImagesDownloadDetails

@{
    ViewBag.Title = "ImagesView";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@{
    <br />
    <div class="container-fluid">
        <div class="row">
            <br /><br />
            <div class="col-sm-8">
                @Html.ActionLink("Ponownie ładuj obraz", "uploadFile", "Images", null, new { @class = "btn btn-primary btn-lg" })
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            @{
                if (ViewBag.Message != null)
                {
                    <div class="alert alert-success">
                        <p>@ViewBag.Message</p>
                    </div>
                }
            }
        </div>
    </div>

    foreach (string file in Model.items)
    {
        <div class="container-fluid">
            <div>
                @{
                    string imPath = "";
                    if (file.Equals(serwer.Config.ServerConfigurator.originalImageName + Model.originalImageExtension))
                    {
                        <p>
                            <h2>Obraz orginalny</h2>
                            @*@Html.ActionLink("Pobierz", "Download", "Images", new { ImageName = "images.jpg" }) this syntax not working, so be cerreful*@
                            
                            
                            @*@using (@Html.BeginForm("RemoveImage", "Images", FormMethod.Post, new { @class = "", role = "form", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()
                                Model.removeImageName = file.ToString();

                                @Html.HiddenFor(r => r.removeImageName)

                                @Html.ActionLink("Pobierz obraz", "DownloadImage", "Images", routeValues: new { ImageName = @file.ToString() }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                                <input type="submit" value="Usuń" class="btn btn-danger btn-lg" />                                           
                            }*@          
                             @Html.ActionLink("Pobierz obraz", "DownloadImage", "Images", routeValues: new { ImageName = @file.ToString() }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                            </p>

                        //imPath = Url.Content(serwer.Config.ServerConfigurator.usersStorage + User.Identity.Name + serwer.Config.ServerConfigurator.directoryPathSeparator + file) + "?noCache=" + DateTimeOffset.Now.ToUnixTimeMilliseconds();
                        <p>
                            <center>
                                <div class="row">
                                    @*<img class="img-responsive" style="width: 100%;" src="@imPath" />*@
                                    @*<img class="img-responsive" style="width: 100%;" src="@imPath" />*@
                                    <img src="@Url.Action("DownloadImage","Images", new {ImageName = "original.jpg", noCache = DateTimeOffset.Now.ToUnixTimeMilliseconds()})" style="width: 100%; height: 100%;" id="originalImage"/>
                                </div>
                            </center>
                        </p>


                        if (!File.Exists(serwer.Config.ServerConfigurator.usersStorage + User.Identity.Name + serwer.Config.ServerConfigurator.directoryPathSeparator + serwer.Config.ServerConfigurator.processedImageName + Model.processedImageExtension))
                        {
                            <br />
                            <p><h4> Trwa przetwarzanie obrazu. Strona odświeży się automatycznie, gdy przetwarzanie zostanie zakończone. Możesz także ręcznie odświeżyć stronę naciskając klawisz F5.</h4></p>
                        }

                    }
                    else if (file.Equals(serwer.Config.ServerConfigurator.processedImageName + Model.processedImageExtension))
                    {
                        <p>
                            <h2>Obraz przetworzony</h2>
                            @*@Html.ActionLink("Pobierz", "Download", "Images", new { ImageName = "images.jpg" }) this syntax not working, so be cerreful*@

                            @*@using (@Html.BeginForm("RemoveImage", "Images", FormMethod.Post, new { @class = "", role = "form", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()
                                Model.removeImageName = file.ToString();

                                @Html.HiddenFor(r => r.removeImageName)

                                @Html.ActionLink("Pobierz obraz", "DownloadImage", "Images", routeValues: new { ImageName = @file.ToString() }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                                <input type="submit" value="Usuń" class="btn btn-danger btn-lg" />
                            }*@
                            @Html.ActionLink("Pobierz obraz", "DownloadImage", "Images", routeValues: new { ImageName = @file.ToString() }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                        </p>
                        //imPath = Url.Content(serwer.Config.ServerConfigurator.imageStoragePath + User.Identity.Name + "/" + file) + "?noCache=" + DateTimeOffset.Now.ToUnixTimeMilliseconds();
                        <div class="row">
                            @*<img class="img-responsive" style="width: 100%;" id="processedImage" src="@imPath" />*@
                            <img src="@Url.Action("DownloadImage","Images", new {ImageName = "processed.jpg", noCache = DateTimeOffset.Now.ToUnixTimeMilliseconds()})" id="processedImage"  style="width: 100%; height: 100%;" />
                        </div>
                    }
                    else if (file.Equals(serwer.Config.ServerConfigurator.afterProcessingDataFileName + serwer.Config.ServerConfigurator.afterProcessingDataFileExtension) && Model.processedImageDataInJSON != null)
                    {
                        <p>
                            <h2>Dane z przetworzonego obrazu</h2>

                            @{
                                // Below it displays whole content of JSON file
                                dynamic stuff = Newtonsoft.Json.JsonConvert.DeserializeObject(Model.processedImageDataInJSON);
                                foreach (var stuffItem in stuff)
                                {

                                    if (stuffItem.Name.Equals("dlugosciPaleczek"))
                                    {
                                        dynamic stuffInternal = Newtonsoft.Json.JsonConvert.DeserializeObject(Model.processedImageDataInJSON);
                                        foreach (var internalItem in stuffInternal["dlugosciPaleczek"])
                                        {                                    
                                            <div style="color: rgb(@internalItem[2], @internalItem[3], @internalItem[4])">
                                                <strong>
                                                    Pałeczka nr @internalItem[0] - @internalItem[1]
                                                </strong>
                                            </div>
                                        }
                                    }
                                    else
                                    {
                                        <div><strong>@stuffItem.Name: </strong>@stuffItem.Value</div>
                                    }
                                }
                                <strong>Uwaga - algorytm "całe szkiełko" zwraca długość próbki w milimetrach. Pozostałe zwracają procentową długość w stosunku do całego obrazu</strong>
                                <br />
                            }
                            <br />
                            @Html.ActionLink("Pobierz dane", "DownloadImage", "Images", routeValues: new { ImageName = @file.ToString() }, htmlAttributes: new { @class = "btn btn-success btn-lg" })
                        </p>
                    }
                    else
                    {
                        // DateTimeOffset.Now.ToUnixTimeMilliseconds() is used to prevent caching images in browsers
                        // this "imPath" - path to the personal original image
                        //imPath = Url.Content(serwer.Config.ServerConfigurator.imageStoragePath + User.Identity.Name + "/" + file) + "?noCache=" + DateTimeOffset.Now.ToUnixTimeMilliseconds();
                    @*<div class="row" id="processedImage">
                        <img class="img-responsive" style="width: 100%;" src="@imPath" />
                    </div>*@
                    }

                }
            </div>
            @*<div class="row">
                <img class="img-responsive col-sm-8" src="@imPath" />
            </div>*@
        </div>
    }

    
    <script type="text/javascript">
        var protocol = window.location.protocol;
        var domain = window.location.hostname;
        var port = window.location.port;

        var url = protocol + "//" + domain + ":" + port + "/MobileDevices/checkIfProcessingIsFinished";
        var reloadFlag = false;

        // Shorthand for $( document ).ready()
        $(function () {
            if ($("#originalImage").length != 0) { 
                $.ajax({
                    url: url,
                    method: "POST",
                    statusCode: {
                        404: function () {
                            setTimeout(checkIfProcessingIsFinished, 1000); // you could choose not to continue on failure...
                        },
                        200: function () {
                            if ($("#processedImage").length === 0)
                                location.reload();
                            console.log("OK");
                        }
                    }
                });
            }
        });

        function checkIfProcessingIsFinished() {
            $.ajax({
                url: url,
                method: "POST",
                statusCode: {
                    404: function () {
                        console.log("Waiting for processed image!");
                        setTimeout(checkIfProcessingIsFinished, 1000); // you could choose not to continue on failure...
                    },
                    200: function () {
                        location.reload();
                    }
                }
            });
        }
    </script>
    
}

server/serwer/serwer/Views/Images/UploadFile.cshtml
@using serwer.Models
@model UploadFileViewModel
@{
    ViewBag.Title = "Załaduj obraz";
}

<h2>Załaduj obraz</h2>

@using (Html.BeginForm("UploadFile", "Images", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div>        

        <div class="form-group">
            @Html.Label("Algorytm obróbki", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(d => d.selectedAlgorithm,

                                        //new SelectList(Model.algorithms.Items, "Value", "Text", Model.algorithms.SelectedValue), 
                                        new SelectList(Model.algorithms, "Key", "Value"),

                                        new { @class = "btn btn-default" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.Label("Plik", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBox("file", "", new { @type = "file", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Prześlij na serwer" class="btn btn-primary" />
            </div>
        </div>
        @{
            if (ViewBag.Message != null)
            {
                <div class="alert alert-success">
                    <p>@ViewBag.Message</p>
                </div>
            }
        }      

    </div>

}